96 - Allow CSV Files
McMaster-Baja-Racing/Better-Data-Viewer pull request #109
Opened 2024-04-01 23:07 UTC by camdnnn

[x] Fixed issue where csv files without gps time given were not able to be graphed
[x] Improved handling of datetime to make sure that all files are timestamp and have a defined timespan

2024-04-02 18:19 UTC, gr812b requested changes
I can't seem to get the datetime stuff working on CSVs inside a bin folder with the data there.

My setup > Uploaded a bin and single csv, asked the chart to show me a file from the bin, the time starts at 0 on the x-axis.
Expected -> any graphs without that lone csv should have the shifted datetime?

2024-04-02 18:24 UTC, camdnnn commented
> I can't seem to get the datetime stuff working on CSVs inside a bin folder with the data there.
> 
> 
> 
> My setup > Uploaded a bin and single csv, asked the chart to show me a file from the bin, the time starts at 0 on the x-axis.
> 
> Expected -> any graphs without that lone csv should have the shifted datetime?


There is a separate issue for adding the feature of manually synching the CSVs to video. The referenced bug issue is to fix that currently and error occurs when trying to use standalone CSV files. That is fixed and the behaviour you mentioned is the intended behaviour for now since we don't have the ability yet to manually sync it and it has no gps data to auto sync 

Here is the link to the issue for the manual synching: https://github.com/McMaster-Baja-Racing/Better-Data-Viewer/issues/95

2024-04-02 18:29 UTC, camdnnn commented
> > I can't seem to get the datetime stuff working on CSVs inside a bin folder with the data there.
> > 
> > 
> > 
> > My setup > Uploaded a bin and single csv, asked the chart to show me a file from the bin, the time starts at 0 on the x-axis.
> > 
> > Expected -> any graphs without that lone csv should have the shifted datetime?
> 
> 
> There is a separate issue for adding the feature of manually synching the CSVs to video. The referenced bug issue is to fix that currently an error occurs when trying to use standalone CSV files. That is fixed and the behaviour you mentioned is the intended behaviour for now since we don't have the ability yet to manually sync it and it has no gps data to auto sync 
> 
> Here is the link to the issue for the manual synching: https://github.com/McMaster-Baja-Racing/Better-Data-Viewer/issues/95

Nvm I misunderstood what you said, I'll look into it

2024-04-02 18:42 UTC, camdnnn commented
> I can't seem to get the datetime stuff working on CSVs inside a bin folder with the data there.
> 
> My setup > Uploaded a bin and single csv, asked the chart to show me a file from the bin, the time starts at 0 on the x-axis. Expected -> any graphs without that lone csv should have the shifted datetime?

Fixed now

2024-04-02 19:36 UTC, gr812b commented
Fix looks good 👍 
Could we set the graph x-axis to still be datetime, but just without the shifting? I like it represented in hours rather than numbers like 4500k and whatnot. This would be on a graph with timestamp (ms) on x-axis but one or more of the files are not in a folder

2024-04-02 20:19 UTC, camdnnn commented
> Fix looks good 👍 Could we set the graph x-axis to still be datetime, but just without the shifting? I like it represented in hours rather than numbers like 4500k and whatnot. This would be on a graph with timestamp (ms) on x-axis but one or more of the files are not in a folder

But the the date is wrong :(
![image](https://github.com/McMaster-Baja-Racing/Better-Data-Viewer/assets/67480325/195e1c39-0f06-4ca0-9f71-77dbb35afa46)

2024-04-03 04:34 UTC, gr812b commented
Check out both 
- Tooltip.formatter https://api.highcharts.com/highcharts/tooltip.formatter
- xaxis.dateTimeLabelFormatter https://api.highcharts.com/highstock/xAxis.dateTimeLabelFormats
Combining these should let us only show the HH:SS on both as we desire here. Maybe dont need to fiddle with dateTimeLabelFormatter as we never have data wide enough to show date on x-axis, but the tooltip does

2024-04-03 08:12 UTC, boktroioi approved these changes

2024-04-04 01:14 UTC, camdnnn commented
> Check out both
> 
> * Tooltip.formatter https://api.highcharts.com/highcharts/tooltip.formatter
> * xaxis.dateTimeLabelFormatter https://api.highcharts.com/highstock/xAxis.dateTimeLabelFormats
>   Combining these should let us only show the HH:SS on both as we desire here. Maybe dont need to fiddle with dateTimeLabelFormatter as we never have data wide enough to show date on x-axis, but the tooltip does

Separate datetime formatting has been added for partial datetime charts

2024-04-04 07:06 UTC, gr812b commented
Would this work on files in folders but that don't have datetime information in them? This edge case could happen with other people saving data to bin files, then the parser parsing it. (Specifically happened tonight)

2024-04-04 17:05 UTC, camdnnn commented
> Would this work on files in folders but that don't have datetime information in them? This edge case could happen with other people saving data to bin files, then the parser parsing it. (Specifically happened tonight)



> Would this work on files in folders but that don't have datetime information in them? This edge case could happen with other people saving data to bin files, then the parser parsing it. (Specifically happened tonight)

2024-04-04 17:05 UTC, camdnnn commented
> Member

2024-04-04 17:06 UTC, camdnnn commented
> Would this work on files in folders but that don't have datetime information in them? This edge case could happen with other people saving data to bin files, then the parser parsing it. (Specifically happened tonight)

Added a check to the backend that verifies that the timespan can be computed

2024-04-10 23:31 UTC, gr812b requested changes
Doesn't work in expected case, also that change from saying Jan 1 would be nice, will look into

2024-04-10 23:31 UTC, gr812b commented on API/src/main/java/backend/API/FileUploadController.java
> +              if (storageService.canComputeTimespan(parent.toString())) {
If parent is null, error is thrown. Needs to check this before invoking .toString() method. This would activate if you upload a CSV file alone.

2024-04-10 23:33 UTC, gr812b commented on API/src/main/java/backend/API/FileUploadController.java
> +              if (storageService.canComputeTimespan(parent.toString())) {
Resolved with 49f9ef799930ef3c8d302104fb1e5249a2915043

2024-04-10 23:39 UTC, gr812b approved these changes

2024-04-10 23:41 UTC, merged