IMU Feature
McMaster-Baja-Racing/Better-Data-Viewer pull request #142
Opened 2024-11-19 16:53 UTC by gr812b

Added a 3D model mapper, which will allow playback of IMU data

2024-12-07 23:37 UTC, gr812b commented on front-end/src/components/model/ModelViewer.tsx
> +    fetchData(event.target.value).then(setData);
No

2024-12-21 20:56 UTC, camdnnn commented on front-end/src/components/model/Eevee.tsx
> +    loader.load('/Eevee.obj', (object) => {
instead of using a hardcoded path could this be updated to use asset pathing

2024-12-21 21:02 UTC, camdnnn requested changes
Seems pretty good to me just one small pathing issue that should be updated

2024-12-22 22:30 UTC, camdnnn approved these changes
LGTM!

2024-12-23 19:32 UTC, merged