Example title of a PR
McMaster-Baja-Racing/Better-Data-Viewer pull request #145
Opened 2024-11-26 03:20 UTC by camdnnn

Updated the ReadMe to remove a section that is incorrect

2024-11-26 22:16 UTC, t-wing11 approved these changes
LGTM

2024-11-26 23:01 UTC, camdnnn commented on backend/README.md
> -## Creating a native executable
Example comment

2024-11-27 02:56 UTC, gr812b requested changes
AHHHHHH THIS IS SO BAD NO NONONO PLEASE NOOOO

2024-11-27 02:56 UTC, gr812b commented on backend/README.md
> -
I like this part of the of the code

2024-11-27 16:51 UTC, hydrowoxy commented on backend/README.md
> -## Creating a native executable
Example reply

2024-11-28 05:15 UTC, gr812b approved these changes

2024-11-28 05:18 UTC, merged