analyzers use logger instead of print statements (close #150)
McMaster-Baja-Racing/Better-Data-Viewer pull request #152
Opened 2024-12-02 18:54 UTC by hydrowoxy

2024-12-22 21:43 UTC, gr812b commented
Related to https://github.com/McMaster-Baja-Racing/Better-Data-Viewer/issues/157 in regards to parsing the inputs

2024-12-23 03:40 UTC, camdnnn requested changes
Good implementation and code cleanup, I just think that we should take a second look at the analyzer enum structure and naming

2024-12-23 03:40 UTC, camdnnn commented on backend/src/main/java/com/mcmasterbaja/analyzer/AnalyzerFactory.java
> +  public Analyzer createAnalyzer(AnalyzerEnum type) {
I find this confusing since there is now an AnalyzerEnum and a AnalyzerType

2024-12-23 03:40 UTC, camdnnn commented on backend/src/main/java/com/mcmasterbaja/analyzer/AnalyzerFactory.java
> +        throw new IllegalArgumentException("Invalid analyzer type");
By extension, I also find this a bit a confusing since there is now and AnalyzerEnum and AnalyzerType

2024-12-23 03:40 UTC, camdnnn commented on backend/src/main/java/com/mcmasterbaja/analyzer/AnalyzerType.java
There is probably a good reason for this, I just don't understand why we need a interface of an enum value

2024-12-23 03:40 UTC, camdnnn commented on backend/src/main/java/com/mcmasterbaja/model/AnalyzerParams.java
see my previous comments

2024-12-23 03:40 UTC, camdnnn commented on backend/src/main/java/com/mcmasterbaja/model/AnalyzerEnum.java
Is there a better way of doing this such that we don't need to define a new enum value for each new Analyzer that we add? I feel like it would be better to avoid having this structure

2024-12-23 03:40 UTC, camdnnn commented on backend/src/main/java/com/mcmasterbaja/model/AnalyzerEnum.java
> +public enum AnalyzerEnum {
I've already said it many times already but I think that we could come up with a better naming or structure for this. I don't like the type being called Enum

2024-12-23 18:59 UTC, gr812b commented on backend/src/main/java/com/mcmasterbaja/analyzer/AnalyzerType.java
This is actually a qualifier, basically used to annotate beans with a more specific naming when injecting them

2024-12-23 19:00 UTC, gr812b commented on backend/src/main/java/com/mcmasterbaja/model/AnalyzerEnum.java
Enum is def the best way, we need to have some way to represent the possible options to our clients (any who call the backend). Enum is incredibly standard for this purpose.

2024-12-23 19:07 UTC, gr812b commented on backend/src/main/java/com/mcmasterbaja/model/AnalyzerEnum.java
I believe the alternative would be using strings, such as "sum" or such. I think the biggest downside is not having a strict list of acceptable options here. An enum is much more type safe.

For this PR, were it a string, we'd be able to use the @Named annotation rather than this custom one

2024-12-23 19:21 UTC, camdnnn approved these changes
LGTM!

2024-12-25 20:59 UTC, merged