6 most analyzers dont work with third column or more
McMaster-Baja-Racing/Better-Data-Viewer pull request #55
Opened 2023-11-22 01:36 UTC by JAWalmsley

still testing, this is a draft

2023-11-22 03:29 UTC, JAWalmsley commented
As far as I can tell it works exactly the same as before, but now analyzers can be applied to datasets with more than 2 columns (GPS date stuff is the only example right now).

Also fixed a big in [d9124e7](https://github.com/McMaster-Baja-Racing/Better-Data-Viewer/pull/55/commits/d9124e7d89c7b95acf5ab576df3da40d39f25d55) where the output filename for accelcurve had a "/" in it so the backend would error trying to read it

2023-11-22 06:04 UTC, gr812b requested changes
Only major change is to the linear interpolator, 

also worth looking into in the future refactoring how the data is passed to /analyze on the controller, perhaps we can structure it in a similar manner to the /files method. Nothing on this needs to be changed as of now though

2023-11-29 01:31 UTC, JAWalmsley commented on API/src/main/java/backend/API/analyzer/LinearInterpolaterAnalyzer.java
>          dataPoints.add(dataPoint);
Should be doing this now, enjoy that 60 char long filename

2023-11-29 01:38 UTC, JAWalmsley commented on API/src/main/java/backend/API/analyzer/LinearMultiplyAnalyzer.java
> +    public LinearMultiplyAnalyzer(String[] inputFiles, String[] inputColumns, String[] outputFiles, double m, double b) {
just fixed

2023-11-29 01:43 UTC, JAWalmsley commented on API/src/main/java/backend/API/analyzer/LinearMultiplyAnalyzer.java
>          }
fixed :)

2023-11-29 01:44 UTC, JAWalmsley commented on API/src/main/java/backend/API/analyzer/LinearInterpolaterAnalyzer.java
>          dataPoints.add(dataPoint);
[0387616](https://github.com/McMaster-Baja-Racing/Better-Data-Viewer/pull/55/commits/0387616631f7b3fe85c104fea3565691a74cb668)

2023-11-29 01:44 UTC, JAWalmsley commented on API/src/main/java/backend/API/analyzer/LinearMultiplyAnalyzer.java
> +    public LinearMultiplyAnalyzer(String[] inputFiles, String[] inputColumns, String[] outputFiles, double m, double b) {
[b1ea9a4](https://github.com/McMaster-Baja-Racing/Better-Data-Viewer/pull/55/commits/b1ea9a429a9c7228461672b43300eab08a690ac6)

2023-11-29 01:44 UTC, JAWalmsley commented on API/src/main/java/backend/API/analyzer/LinearMultiplyAnalyzer.java
>          }
[bab1908](https://github.com/McMaster-Baja-Racing/Better-Data-Viewer/pull/55/commits/bab190840c40de3896a3a03752be756883dd5f17)

2023-11-29 23:23 UTC, gr812b requested changes
Overall looks great, I'm just curious on the behaviour if we can merge main into this branch and test with XYColour. Looks like it should make sense to fetch, but not 100% certain

2023-11-29 23:23 UTC, gr812b commented on front-end/src/components/Chart.js
> +        // TODO: Remove debug code
Worth removing soon

2023-12-02 22:24 UTC, JAWalmsley commented
Merge works, but workflow for linear interpolation should probably be reworked because right now we need to first make the file two columns at a time in Line, then graph it in XYColour

2023-12-07 01:35 UTC, merged